VFS-40, zmiana podejścia, kompletne przepisanie skryptow gen_dev i gen_test, usuniecie niepotrzebnych juz plikow, update makefile i readme.

diff --git a/gen_dev b/gen_dev
--- a/gen_dev
+++ b/gen_dev
@@ -1,161 +1,196 @@
 #!/bin/bash
 
-if [ $# -eq 1 ] && [ $1 == "-clean_up" ]; then
-	mv releases/old_reltool.config releases/reltool.config 2>/dev/null
-	mv releases/old_vars.config releases/vars.config 2>/dev/null
-	exit 0
-fi
+# Display usage help
+error_bad_args()
+{
+	echo "Usage:"
+	echo "variant 1: (argument order can be arbitrary)"
+	echo "	$0 -name node_name@host -main_ccm main_ccm_node@host [-opt_ccms opt_ccm_node1@host opt_ccm_node2@host ...] -db_nodes dbnode1@host dbnode2@host ..."
+	echo " "
+	echo "variant 2: (file 'gen_dev.args' with arguments present in script directory)"
+	echo "	$0"
+	echo " "
+	echo "Additional parameters: (acceptable in both variants)"
+	echo "-no_compile -> skip code compilation straight to release generation."
+	echo "-no_generate -> skip code compilation and release generation (creates a copy of existing release)."	
+	exit 1	
+}
 
-# Simple validation of arguments
-if [ $# -lt 4 ] || [ $1 != "-name" ] || [ $3 != "-main_ccm" ]; then
+# Function used to retrieve a parameter from script arguments. 
+# args: 
+# $1: <<script arguments>>   (arguments passed to the script; $*)
+# $2: <<token of desired parameter>>    (eg. '-main_ccm' to retrieve main ccm name)
+# $3: <<single|list>>      (expecting result as a single term or a list?)
+# 
+# The function starts reading parameters after ocurrence of desired token and continues for one word (single) or until it stumbles upon
+# another token starting with '-' or end of line (list)
+get_parameter_from_args()
+{
+	local ARGS=$1
+	local TOKEN=$2
+	local RETURN_OPTION=$3
 
-	# Check for .args file
-	if [ $# -eq 0 ] && [ -f gen_dev.args ]; then
-		ARGS=`cat gen_dev.args`
-		echo 'Using arguments from gen_dev.args'
-		./gen_dev $ARGS
-		exit 0
-	
-	# Invalid arguments or absence of .args file
+	# Find the occurence of desired token. If there isn't one, there was no parameter value specified = error. 
+	# Exception: -opt_ccms could have been left empty intentionally.
+	local INDEX=`awk -v a=" $ARGS " -v b=" $TOKEN " 'BEGIN{print index(a, b)}'`
+	if [[ $INDEX -eq 0 ]]; then
+		if [[ $TOKEN == '-opt_ccms' ]]; then
+			RESULT=""
+			return
+		else
+			echo " "
+			echo "Error: missing parameter"
+			echo "'$TOKEN' must occur in script arguments."
+			echo "Terminating."
+			echo " "
+			error_bad_args
+			exit 1
+		fi
+	fi
+
+	# Trim the arguments string so that it starts after the token
+	local ARGS=${ARGS:$(($INDEX + ${#TOKEN})):${#ARGS}}
+
+	# Find the next occurence of a hyphen 
+	INDEX=`awk -v a="$ARGS" -v b="-" 'BEGIN{print index(a, b)}'`
+
+	# If its zero, the ARGS variable holds the desired string. If not, cut off the part after the hyphen
+	if [[ $INDEX -gt 0 ]]; then
+		ARGS=${ARGS:0:$(($INDEX - 1))}
+	fi
+
+	# If the expected result is a single word, get the first one from remaining string. 
+	# This somehow resolves errors like passing a double word 'name' parameter.
+	if [[ $RETURN_OPTION == "single" ]]; then
+		ARGS=`echo $ARGS | cut -f1 -d' '`
 	else
-		echo "Usage:"
-		echo "	$0 -name node_name@host -main_ccm main_ccm_node@host [-opt_ccm opt_ccm_node1@host opt_ccm_node2@host ...] -db_nodes dbnode1@host dbnode2@host ..."
-		echo " "
-		echo "or:"
-		echo "	$0 (file 'gen_dev.args' containing arguments present in script directory)"
-		echo " "
-		echo "after rebar ./generate:"
-		echo "	$0 -clean_up (restores reltool.config to the original state)"
-		exit 1
+		ARGS=`echo $ARGS`          # trims spaces from the beginning of the list
+	fi
+
+	# If the result is empty, there was no parameter value specified = error. Exception: -opt_ccms could have been left empty intentionally.
+	if [[ $ARGS == "" ]]; then
+		if [[ $TOKEN == '-opt_ccms' ]]; then
+			RESULT=""
+			return
+		else
+			echo " "
+			echo "Error: missing parameter"
+			echo "'$TOKEN' must occur in script arguments."
+			echo "Terminating."
+			echo " "
+			error_bad_args
+			exit 1
+		fi
+	fi
+
+	# "return" the parameter(s)
+	RESULT=$ARGS
+}
+
+# Enter the script directory
+PATH_TO_SCRIPT=`echo $0 | sed "s/gen_dev//g"`
+cd $PATH_TO_SCRIPT
+
+# Accepting only no args, -no_compile or -no_generate and reading from file. Otherwise all args have to be passed via args
+if [[ $# -eq 0 ]] || 
+	[[ $# -eq 1  && $1 == "-no_compile" ]] || 
+	[[ $# -eq 1  && $1 == "-no_generate" ]]; then
+	# Check for .args file
+	if [[ -f gen_dev.args ]]; then
+		# Get args from 
+		ARGS=`cat gen_dev.args`
+		# And execute the script with the args from there
+		if [[ $1 == "" ]]; then
+			echo "Using arguments from gen_dev.args"
+		else
+			echo "Using arguments from gen_dev.args with $1 option"			
+		fi
+		./gen_dev $ARGS $1
+		exit 0
+	else
+		# Error; no args file
+		error_bad_args
 	fi
 fi
 
 
-# Variables with node name and main CCM name, initially this node is not a CCM node, string with CCM nodes initialized with main CCM
-NODE_NAME=$2
-AT_INDEX=`expr index "$2" @`
-NODE_NAME_WITHOUT_HOSTNAME=${NODE_NAME:0:(($AT_INDEX - 1))}
-MAIN_CCM_NAME=$4
-IS_THIS_CCM=0
-CCM_LIST="[\\\\\"\\\\\\\\'$MAIN_CCM_NAME\\\\\\\\'\\\\\""
+#####################################
+# GATHER ARGS
 
-# Get local IP address (used as cookie)
-IFCONFIG_LINE=`ifconfig | grep "inet addr:.*Bcast:"`
-COLON_INDEX=`expr index "$IFCONFIG_LINE" :`
-BCAST_INDEX=`expr index "$IFCONFIG_LINE" Bcast`
-COOKIE=${IFCONFIG_LINE:COLON_INDEX:((BCAST_INDEX - 2))}
+# Get node name from script args
+get_parameter_from_args "$*" -name single
+NODE_NAME=$RESULT
 
-# Check if this node is the main CCM node
-if [ $NODE_NAME == $MAIN_CCM_NAME ]; then
-	IS_THIS_CCM=1
-fi
+# Get main_ccm name from script args
+get_parameter_from_args "$*" -main_ccm single
+MAIN_CCM=$RESULT
 
-if [ $5 == "-opt_ccm" ]; then
-	# Create list of CCM node names and check if this node is one of CCMs, break when -db_nodes is stumbled upon
-	for (( INDEX=6; INDEX<=$#; INDEX++ ))
-	do
-		if [ "-db_nodes" == ${!INDEX} ]; then
-			DB_NODES_LIST_INDEX=$(($INDEX + 1))
-			break;
-		fi
+# Get opt_ccms from script args
+get_parameter_from_args "$*" -opt_ccms list
+OPT_CCMS=$RESULT
 
-		CCM_LIST="$CCM_LIST,\\\\\"\\\\\\\\'${!INDEX}\\\\\\\\'\\\\\""
-		if [ $NODE_NAME == ${!INDEX} ]; then
-			IS_THIS_CCM=1
-		fi
-	done
+# Get db_nodes from script args
+get_parameter_from_args "$*" -db_nodes list
+DB_NODES=$RESULT
+
+# Get short node name (without hostname)
+AT_INDEX=`expr index "$NODE_NAME" @`
+if [[ $AT_INDEX -gt 0 ]]; then
+	NODE_NAME_WITHOUT_HOSTNAME=${NODE_NAME:0:(($AT_INDEX - 1))}
 else
-	# No opt ccms, move to db nodes
-	DB_NODES_LIST_INDEX=6
+	NODE_NAME_WITHOUT_HOSTNAME=$NODE_NAME
 fi
-CCM_LIST="$CCM_LIST]"
 
-# Create list od DBMS nodes
-DB_NODES_LIST="[\\\\\"\\\\\\\\'${!DB_NODES_LIST_INDEX}\\\\\\\\'\\\\\""
-DB_NODES_LIST_INDEX=$(($DB_NODES_LIST_INDEX + 1))
-for (( INDEX=DB_NODES_LIST_INDEX; INDEX<=$#; INDEX++ ))
-do
-	DB_NODES_LIST="$DB_NODES_LIST,\\\\\"\\\\\\\\'${!INDEX}\\\\\\\\'\\\\\""
-done
-DB_NODES_LIST="$DB_NODES_LIST]"
+echo " "
+echo "========================================"
+echo "Generating release for $NODE_NAME in    /releases/$NODE_NAME_WITHOUT_HOSTNAME"
 
-# Store original vars.config and reltool.config to be able to restore them
-cp releases/vars.config releases/old_vars.config
-cp releases/reltool.config releases/old_reltool.config
+# Skip generation if -no_generate is in args
+INDEX=`awk -v a=" $* " -v b=" -no_generate " 'BEGIN{print index(a, b)}'`
+if [[ $INDEX -eq 0 ]]; then
 
-case $IS_THIS_CCM in
-	# This node is a worker
-	0)
-		# Produce a proper vars.config file from template
-		sed "s/\$CCM_LIST/$CCM_LIST/g; 
-			s/\$NODE_NAME/$NODE_NAME/g; 
-			s/\$DB_NODES_LIST/$DB_NODES_LIST/g; 
-			s/\$COOKIE/$COOKIE/g; 
-			/%%%/d" "releases/vars/worker_vars.config" > releases/vars.config
-		;;
+	# Skip compilation if -no_compile is in args
+	INDEX=`awk -v a=" $* " -v b=" -no_compile " 'BEGIN{print index(a, b)}'`
+	if [[ $INDEX -eq 0 ]]; then
+		# Compile the code
+		./rebar compile
+	fi
 
+	# Generate the release
+	./rebar generate
+else
+	# User requested to skip release generation
+	if [[ ! -d releases/veil_cluster_node ]]; then
+		echo "Error: no release found"
+		echo "Cannot skip release generation - no release package found."
+		echo "Try executing the script without -no_generate option."
+		echo "Terminating."
+		exit 1
+	fi
+fi
 
-	# This node is a CCM 
-	1)
-		# The list with two elements - main CCM name and tuple with optional CCMs
-		CCM_HIERARCHY_LIST="['$MAIN_CCM_NAME', {"
-		if [ $# -gt 5 ]; then
-			for (( INDEX=6; INDEX<=$#; INDEX++ ))
-			do
-				if [ "-db_nodes" == ${!INDEX} ]; then
-					break;
-				fi
+# Remove old release
+rm -r releases/$NODE_NAME_WITHOUT_HOSTNAME 2>/dev/null
 
-				CCM_HIERARCHY_LIST="$CCM_HIERARCHY_LIST'${!INDEX}'"
+# Copy the release package to proper location (directory named as the node without hostname), preserve mode
+cp -R -p releases/veil_cluster_node releases/$NODE_NAME_WITHOUT_HOSTNAME
 
-				NEXT=$((INDEX + 1))
-				if [ ${!NEXT} != "-db_nodes" ]; then
-					CCM_HIERARCHY_LIST="$CCM_HIERARCHY_LIST, "
-				fi
-			done
-		fi
-		CCM_HIERARCHY_LIST="$CCM_HIERARCHY_LIST}]"
+# Execute the apply_config script with proper arguments
+./releases/$NODE_NAME_WITHOUT_HOSTNAME/config/apply_config -name $NODE_NAME -main_ccm $MAIN_CCM -opt_ccms $OPT_CCMS -db_nodes $DB_NODES
 
-		# The list with CCMs to synchronize with, skip own node name
-		SYNC_CCM_LIST="["
-		if [ $NODE_NAME != $MAIN_CCM_NAME ]; then
-			if [ $7 == "-db_nodes" ]; then
-				SYNC_CCM_LIST="['$MAIN_CCM_NAME'"
-			else
-				SYNC_CCM_LIST="['$MAIN_CCM_NAME', "
-			fi
-		fi
-		if [ $# -gt 5 ]; then
-			for (( INDEX=6; INDEX<=$#; INDEX++ ))
-			do
-				if [ ${!INDEX} == "-db_nodes" ]; then
-					break;
-				fi
+# Get IP address to use it as the cookie
+IFCONFIG_LINE=`ifconfig | grep "inet addr:.*Bcast:"`
+COLON_INDEX=`awk -v a="$IFCONFIG_LINE" -v b=":" 'BEGIN{print index(a, b)}'`
+BCAST_INDEX=`awk -v a="$IFCONFIG_LINE" -v b="Bcast" 'BEGIN{print index(a, b)}'`
+COOKIE=${IFCONFIG_LINE:COLON_INDEX:((BCAST_INDEX - COLON_INDEX - 3))}
 
-				if [ ${!INDEX} != $NODE_NAME ]; then
-					SYNC_CCM_LIST="$SYNC_CCM_LIST'${!INDEX}'"
+# Get application version
+START_ERL=`cat releases/$NODE_NAME_WITHOUT_HOSTNAME/releases/start_erl.data`
+APP_VSN=${START_ERL#* }
 
-					NEXT=$((INDEX + 1))
-					if [ ${!NEXT} != $NODE_NAME ] && [ ${!NEXT} != "-db_nodes" ]; then
-						SYNC_CCM_LIST="$SYNC_CCM_LIST, "
-					fi
-				fi
-			done
-		fi
-		SYNC_CCM_LIST="$SYNC_CCM_LIST]"
+# Replace the cookie
+sed -i "s/-setcookie.*/-setcookie '$COOKIE'/g" releases/$NODE_NAME_WITHOUT_HOSTNAME/releases/$APP_VSN/vm.args
 
-		# produce a proper vars.config file from template
-		sed "s/\$CCM_HIERARCHY_LIST/$CCM_HIERARCHY_LIST/g; 
-			s/\$SYNC_CCM_LIST/$SYNC_CCM_LIST/g; 
-			s/\$CCM_LIST/$CCM_LIST/g; 
-			s/\$NODE_NAME/$NODE_NAME/g; 
-			s/\$DB_NODES_LIST/$DB_NODES_LIST/g; 
-			s/\$COOKIE/$COOKIE/g; 
-			/%%%/d" "releases/vars/ccm_vars.config" > releases/vars.config
-		;;
-esac
-
-# Change target dir in reltool.config
-sed -i "s/{target_dir,.*\\./{target_dir, \"$NODE_NAME_WITHOUT_HOSTNAME\"}./g" "releases/reltool.config"
+echo "Cookie set to: $COOKIE"
 
 exit 0
diff --git a/gen_test b/gen_test
--- a/gen_test
+++ b/gen_test
@@ -1,125 +1,208 @@
 #!/bin/bash
 
-function bad_args_error
+# Display usage help
+error_bad_args()
 {
 	echo "Usage:" 
-	echo "	$0 -worker worker1@host worker2@host ... -main_ccm main_ccm_node@host [-opt_ccm opt_ccm_node1@host opt_ccm_node2@host ...] -db_nodes dbnode1@host dbnode2@host ... [-start]"
+	echo "variant 1: (argument order can be arbitrary)"
+	echo "	$0 -workers worker1@host worker2@host ... -main_ccm main_ccm_node@host [-opt_ccms opt_ccm_node1@host opt_ccm_node2@host ...] -db_nodes dbnode1@host dbnode2@host ..."
 	echo " "
-	echo "or:"
-	echo "	$0 [-start] (file 'gen_test.args' containing arguments present in script directory)"
+	echo "variant 2: (file 'gen_test.args' with arguments present in script directory)"
+	echo "	$0"
 	echo " "
-	echo "adding option -start will cause the script to start test environment according to arguments, skipping release generation"
+	echo "Additional parameters: (acceptable in both variants)"
+	echo "-start -> start test environment immediately after generation"
+	echo "-start_no_generate -> start test environment according to arguments, skipping the generation (only after generating one)"
 	exit 1	
 }
 
-if [ $# -lt 4 ] || [ $1 != "-worker" ]; then
+# Function used to retrieve a parameter from script arguments. 
+# args: 
+# $1: <<script arguments>>   (arguments passed to the script; $*)
+# $2: <<token of desired parameter>>    (eg. '-main_ccm' to retrieve main ccm name)
+# $3: <<single|list>>      (expecting result as a single term or a list?)
+# 
+# The function starts reading parameters after ocurrence of desired token and continues for one word (single) or until it stumbles upon
+# another token starting with '-' or end of line (list)
+get_parameter_from_args()
+{
+	local ARGS=$1
+	local TOKEN=$2
+	local RETURN_OPTION=$3
 
-	# Check for .args file
-	if [ $# -lt 2 ] && [ -f gen_test.args ]; then
-		ARGS=`cat gen_test.args`
-		echo 'Using arguments from gen_test.args'
-		if [ $# -eq 1 ] && [ $1 == "-start" ]; then
-			./gen_test $ARGS -start
-		elif [ $# -eq 0 ]; then
-			./gen_test $ARGS
+	# Find the occurence of desired token. If there isn't one, there was no parameter value specified = error. 
+	# Exception: -opt_ccms could have been left empty intentionally.
+	local INDEX=`awk -v a=" $ARGS " -v b=" $TOKEN " 'BEGIN{print index(a, b)}'`
+	if [[ $INDEX -eq 0 ]]; then
+		if [[ $TOKEN == '-opt_ccms' ]]; then
+			RESULT=""
+			return
 		else
-			bad_args_error
+			echo " "
+			echo "Error: missing parameter"
+			echo "'$TOKEN' must occur in script arguments or 'gen_test.args' file."
+			echo "Terminating."
+			echo " "
+			error_bad_args
+			exit 1
 		fi
-		exit 0
 	fi
 
-	# Invalid arguments or absence of .args file
-	bad_args_error
+	# Trim the arguments string so that it starts after the token
+	local ARGS=${ARGS:$(($INDEX + ${#TOKEN})):${#ARGS}}
+
+	# Find the next occurence of a hyphen 
+	INDEX=`awk -v a="$ARGS" -v b="-" 'BEGIN{print index(a, b)}'`
+
+	# If its zero, the ARGS variable holds the desired string. If not, cut off the part after the hyphen
+	if [[ $INDEX -gt 0 ]]; then
+		ARGS=${ARGS:0:$(($INDEX - 1))}
+	fi
+
+	# If the expected result is a single word, get the first one from remaining string. 
+	# This somehow resolves errors like passing a double word 'name' parameter.
+	if [[ $RETURN_OPTION == "single" ]]; then
+		ARGS=`echo $ARGS | cut -f1 -d' '`
+	else
+		ARGS=`echo $ARGS`          # trims spaces from the beginning of the list
+	fi
+
+	# If the result is empty, there was no parameter value specified = error. Exception: -opt_ccms could have been left empty intentionally.
+	if [[ $ARGS == "" ]]; then
+		if [[ $TOKEN == '-opt_ccms' ]]; then
+			RESULT=""
+			return
+		else
+			echo " "
+			echo "Error: missing parameter"
+			echo "'$TOKEN' must occur in script arguments or 'gen_test.args' file."
+			echo "Terminating."
+			echo " "
+			error_bad_args
+			exit 1
+		fi
+	fi
+
+	# "return" the parameter(s)
+	RESULT=$ARGS
+}
+
+
+# Enter the script directory
+PATH_TO_SCRIPT=`echo $0 | sed "s/gen_test//g"`
+cd $PATH_TO_SCRIPT
+
+# Accepting only no args, -start or -start_no_generate and reading from file. Otherwise all args have to be passed via args
+if [[ $# -eq 0 ]] || 
+	[[ $# -eq 1  && $1 == "-start" ]] || 
+	[[ $# -eq 1  && $1 == "-start_no_generate" ]]; then
+	# Check for .args file
+	if [[ -f gen_dev.args ]]; then
+		# And execute the script with the args from there
+		ARGS=`cat gen_test.args`
+		if [[ $1 == "" ]]; then
+			echo "Using arguments from gen_test.args"
+		else
+			echo "Using arguments from gen_test.args with $1 option"			
+		fi
+		./gen_test $ARGS $1
+		exit 0
+	else
+		# Error; no args file
+		error_bad_args
+	fi
 fi
 
 
-for (( INDEX=2; INDEX<=$#; INDEX++ ))
-do
-	# List ends at -main_ccm 
-	if [ ${!INDEX} == "-main_ccm" ]; then
-		NEXT_LOOP_INDEX=$((INDEX + 2))
-		INDEX_PLUS_ONE=$((INDEX + 1))
+#####################################
+# GATHER ARGS
 
-		# Check if required main CCM name occurs
-		if [ $# -lt $INDEX_PLUS_ONE ]; then
-			bad_args_error
-		fi
-		MAIN_CCM_NAME=${!INDEX_PLUS_ONE}
+# Get worker list from script args
+get_parameter_from_args "$*" -workers list
+WORKERS=$RESULT
 
-		# Append main ccm to node list
-		NODE_LIST[(( INDEX - 2))]=$MAIN_CCM_NAME
-		break
-	fi
+# Get main_ccm name from script args
+get_parameter_from_args "$*" -main_ccm single
+MAIN_CCM=$RESULT
 
-	# Append worker to node list
-	NODE_LIST[(( INDEX - 2))]=${!INDEX}
-done
+# Get opt_ccms from script args
+get_parameter_from_args "$*" -opt_ccms list
+OPT_CCMS=$RESULT
 
+# Get db_nodes from script args
+get_parameter_from_args "$*" -db_nodes list
+DB_NODES=$RESULT
+
+# Initially, don't start the environment
 DO_START=0
-if [ ${!#} == "-start" ]; then
+
+# Check if -start_no_generate option appeared
+INDEX=`awk -v a=" $* " -v b=" -start_no_generate " 'BEGIN{print index(a, b)}'`
+if [[ $INDEX -eq 0 ]]; then
+	# It didn't, generation is needed
+
+	echo " "
+	echo "==================================================================="
+	echo "Generating test environment"
+	echo " "
+
+	# Compile the code and generate the release (it's needed only once, then the package will be copied proper amount of times)
+	./rebar compile
+	./rebar generate
+
+	# Generate releases for all nodes
+	ALL_NODES="$WORKERS $MAIN_CCM $OPT_CCMS"
+	for NODE in $ALL_NODES
+	do
+		./gen_dev -name $NODE -main_ccm $MAIN_CCM -opt_ccms $OPT_CCMS -db_nodes $DB_NODES -no_generate
+	done
+
+	echo " "
+	echo "Test environment generated succesfully."
+else
+	# It did, do the starting
 	DO_START=1
 fi
 
-for (( INDEX=$((NEXT_LOOP_INDEX + 1)); INDEX<=$#; INDEX++ ))
-do
-	if [ ${!INDEX} == '-db_nodes' ]; then		
-		NEXT_LOOP_INDEX=$((INDEX + 1))
-		break;
-	fi
-	OPT_CCM_LIST="$OPT_CCM_LIST ${!INDEX}"
-	NODE_LIST[(( INDEX - 4))]=${!INDEX}
-done
-
-for (( INDEX=$NEXT_LOOP_INDEX; INDEX<=$#; INDEX++ ))
-do
-	DB_NODES_LIST="$DB_NODES_LIST ${!INDEX}"
-done
-
-if [ $DO_START -eq 0 ]; then
-	for NODE in "${NODE_LIST[@]}"
-	do
-		AT_INDEX=`expr index "$NODE" @`
-		NODE_NAME_WITHOUT_HOSTNAME=${NODE:0:(($AT_INDEX - 1))}
-		echo " "
-		echo "--------------------------------------------"
-		echo "generating release for $NODE in   releases/$NODE_NAME_WITHOUT_HOSTNAME"
-		echo " "
-		make release_config args="-name $NODE -main_ccm $MAIN_CCM_NAME -opt_ccm $OPT_CCM_LIST -db_nodes $DB_NODES_LIST"
-
-        if [ $? -ne 0 ]; then
-            echo ""
-            echo "Error during generation of a release. Make sure all dependencies are present in project directory."
-            exit
-        fi
-
-		echo " "
-		echo "done!"
-	done	
-
-	echo " "
-	echo "Test environment successfully set up!" 
-
-else
-	echo " "
-	echo "--------------------------------------------"
-	echo " "
-	for NODE in "${NODE_LIST[@]}"
-	do
-		AT_INDEX=`expr index "$NODE" @`
-		NODE_NAME_WITHOUT_HOSTNAME=${NODE:0:(($AT_INDEX - 1))}
-		echo "starting $NODE in   releases/$NODE_NAME_WITHOUT_HOSTNAME"
-		make start_config node="$NODE_NAME_WITHOUT_HOSTNAME"
-
-        if [ $? -ne 0 ]; then
-            echo ""
-            echo "Error during start of a node. Is the test environment ready?"
-            exit
-        fi
-	done
-	echo " "
-	echo "Test environment successfully started!" 
+# Check if -start option appeared
+INDEX=`awk -v a=" $* " -v b=" -start " 'BEGIN{print index(a, b)}'`
+if [[ $INDEX -gt 0 ]]; then
+	# It did, do the starting
+	DO_START=1
 fi
 
+if [[ $DO_START -eq 1 ]]; then
+	# Start the environment
+	echo " "
+	echo "==================================================================="
+	echo "Starting test environment"
+	echo " "
+
+
+	# Start all nodes
+	ALL_NODES="$MAIN_CCM $OPT_CCMS $WORKERS"
+	for NODE in $ALL_NODES
+	do
+		# Get short name
+		AT_INDEX=`expr index "$NODE" @`
+		if [[ $AT_INDEX -gt 0 ]]; then
+			NODE_NAME_WITHOUT_HOSTNAME=${NODE:0:(($AT_INDEX - 1))}
+		else
+			# If there is no '@', do nothing
+			NODE_NAME_WITHOUT_HOSTNAME=$NODE
+		fi
+
+		echo "Starting node: $NODE_NAME_WITHOUT_HOSTNAME..."
+		./releases/$NODE_NAME_WITHOUT_HOSTNAME/bin/veil_cluster_node start
+        if [ $? -ne 0 ]; then
+            echo ""
+            echo "Error during start of node $NODE_NAME_WITHOUT_HOSTNAME. Is the test environment ready?"
+            exit 1
+        fi
+	done
+
+	echo " "
+	echo "Test environment started succesfully."	
+fi
 
 exit 0
-
diff --git a/releases/files/apply_config b/releases/files/apply_config
--- a/releases/files/apply_config
+++ b/releases/files/apply_config
@@ -1,18 +1,66 @@
 #!/bin/bash
 
-# Enter the script directory
-PATH_TO_SCRIPT=`echo $0 | sed "s/apply_config//g"`
-cd $PATH_TO_SCRIPT
+display_help()
+{
+	echo "
+Prerequisites
+-------------
 
-# Ensure config file exists
-if [ ! -f config.args ]; then
-	echo " "
-	echo "Error: missing configuration file"
-	echo "'config.args' not found in script directory."
-	echo "Terminating."
-	exit 1
-fi
+Firstly, the user must have execution rights on both '/config/apply_config' and '/bin/veil_cluster_node' scripts.
 
+Secondly, 'config.args' file must be present in 'config' directory (along with 'apply_config' script).
+
+Setting parameters
+------------------
+
+List of parameters that can be set:
+
+    name       -> name of the node (erlang long name)
+    main_ccm   -> main CCM name (of the cluster this node operates in)
+    opt_ccms   -> list of optional CCMs (this parameter is not mandatory)
+    db_nodes   -> list of DBMS nodes
+
+Primarily, these parameters are retrieved from 'config.args' file. It should contain these parameters in following manner:
+
+    <parameter_name>: <parameter_value>
+
+Another way is passing these parameters via command line arguments. In this case the syntax is:
+
+    ./apply_config -<parameter1_name> <parameter1_value> -<parameter2_name> <parameter2_value> ...
+
+NOTE:
+
+* parameters passed via command line OVERRIDE those in 'config.args' file
+* \"command line way\" can specify any subset of parameters, for instance:
+    * './apply_config' will cause the script to use all parameters from 'config.args'
+    * './apply_config -name somename@host.net' will cause the script to use parameters from 'config.args' except node name
+    * './apply_config -opt_ccms' (no opt_ccms value specified) will override opt_ccms from 'config.args' with null value
+* (both) parameter order can be arbitrary
+* (both) multiple values (eg. DBMS nodes) are passed as a space-delimited list (eg. -db_nodes dbnode1@host.net dbnode2@host.net)
+* (both) parameter values can't contain spaces or hyphens
+* (command line) parameter names are preceded by a hyphen; '-'
+
+Starting a release
+------------------
+
+There are three options which are used to start a release. They are passed along with other arguments to the 'apply_config' script.
+
+    -start    -> the script will perform the configuration and then start the node as a daemon
+    -attach   -> the script will skip configuration and try to attach to a running node with an erlang shell (used after -start)
+    -console  -> the script will perform the configuration and then start the node with an erlang shell
+
+If none of these arguments occur, the script will terminate after setting up the configuration.
+
+Full example of usage
+---------------------
+
+    ~$  ./apply_config -name mynode@host.net -main_ccm ccmnode@host.net -console
+
+Above command will configure the release according to 'config.args', except for name and main_ccm which will be modified
+corresponding to command line arguments. Then, the node will be started presenting to the user with an erlang shell."
+
+	exit 0
+}
 
 # Function used to retrieve a parameter from script arguments. 
 # args: 
@@ -29,7 +77,7 @@ get_parameter_from_args()
 	local RETURN_OPTION=$3
 
 	# Find the occurence of desired token. If there isn't one, return with -no_param value.
-	local INDEX=`awk -v a="$ARGS" -v b="$TOKEN" 'BEGIN{print index(a, b)}'`
+	local INDEX=`awk -v a=" $ARGS " -v b=" $TOKEN " 'BEGIN{print index(a, b)}'`
 	if [[ $INDEX -eq 0 ]]; then
 		RESULT="-no_param"
 		return
@@ -47,14 +95,15 @@ get_parameter_from_args()
 	fi
 
 	# If the expected result is a single word, get the first one from remaining string. 
-	# This somehow resolves errors like passing a double 'name' parameter.
+	# This somehow resolves errors like passing a double word 'name' parameter.
 	if [[ $RETURN_OPTION == "single" ]]; then
 		ARGS=`echo $ARGS | cut -f1 -d' '`
 	else
 		ARGS=`echo $ARGS`          # trims spaces from the beginning of the list
 	fi
 
-	if [[ $ARGS == "" ]]; then
+	# If the result is empty, there was no parameter value specified. Exception: -opt_ccms could have been left empty intentionally.
+	if [[ $ARGS == "" ]] && [[ $TOKEN != '-opt_ccms' ]]; then
 		RESULT="-no_param"
 		return
 	fi
@@ -75,6 +124,8 @@ get_parameter_from_file()
 	RESULT=`grep "$TOKEN" config.args`
 	RESULT=${RESULT:${#TOKEN}:${#RESULT}}
 	
+	# If the expected result is a single word, get the first one from remaining string. 
+	# This somehow resolves errors like passing a double word 'name' parameter.
 	if [[ $RETURN_OPTION == "single" ]]; then
 		RESULT=`echo $RESULT | cut -f1 -d' '`
 	else
@@ -88,12 +139,37 @@ get_parameter_from_file()
 		echo "Error: missing parameter"
 		echo "'${TOKEN%?}' must occur in script arguments or 'config.args' file."
 		echo "Terminating."
+		echo " "
+		echo "for usage help, type:"
+		echo "	~$ ./apply_config -help "
 		exit 1
 	fi
 }
 
+# Check for -help otpion
+INDEX=`awk -v a=" $* " -v b=" -help " 'BEGIN{print index(a, b)}'`
+if [[ $INDEX -gt 0 ]]; then
+	display_help
+fi
+
+# Enter the script directory
+PATH_TO_SCRIPT=`echo $0 | sed "s/apply_config//g"`
+cd $PATH_TO_SCRIPT
+
+# Ensure config file exists
+if [ ! -f config.args ]; then
+	echo " "
+	echo "Error: missing configuration file"
+	echo "'config.args' not found in script directory."
+	echo "Terminating."
+	echo " "
+	echo "for usage help, type:"
+	echo "	~$ ./apply_config -help "
+	exit 1
+fi
+
 # Check for '-attach' option. If it occurs, it's logical to assume the node is already running, so no further configuration is needed
-INDEX=`awk -v a="$*" -v b="-attach" 'BEGIN{print index(a, b)}'`
+INDEX=`awk -v a=" $* " -v b=" -attach " 'BEGIN{print index(a, b)}'`
 if [[ $INDEX -gt 0 ]]; then
 
 	# User requested attaching to the node
@@ -133,21 +209,6 @@ if [[ $NODE_NAME == "-no_param" ]]; then
 	NODE_NAME=$RESULT
 fi
 
-
-#####################################
-# NODE TYPE
-
-# Check for node type in script args
-get_parameter_from_args "$*" -node_type single
-NODE_TYPE=$RESULT
-
-# If there was none specified...
-if [[ $NODE_TYPE == "-no_param" ]]; then
-	# ... retrieve node type from config file
-	get_parameter_from_file node_type: single
-	NODE_TYPE=$RESULT
-fi
-
 #####################################
 # MAIN CCM
 
@@ -160,6 +221,13 @@ if [[ $MAIN_CCM == "-no_param" ]]; then
 	# ... retrieve main_ccm name from config file
 	get_parameter_from_file main_ccm: single
 	MAIN_CCM=$RESULT
+fi
+
+# Originally let's assume this node is a worker 
+NODE_TYPE="worker"
+# Check if the node name equals main CCM -> this node is a CCM
+if [[ $NODE_NAME == $MAIN_CCM ]]; then
+	NODE_TYPE="ccm"
 fi
 
 #####################################
@@ -177,11 +245,15 @@ if [[ $OPT_CCMS == "-no_param" ]]; then
 fi
 
 # And turn them into a formatted list, along with main ccm
-OPT_CCMS_ARRAY=$(echo $OPT_CCMS | tr " " "\n")
 CCMS_LIST="[\"\\\'$MAIN_CCM\\\'\","
-for OPT_CCM in $OPT_CCMS_ARRAY
+for OPT_CCM in $OPT_CCMS
 do
     CCMS_LIST="$CCMS_LIST\"\\\'$OPT_CCM\\\'\","
+
+	# Check if the node name equals current CCM -> this node is a CCM
+	if [[ $NODE_NAME == $OPT_CCM ]]; then
+		NODE_TYPE="ccm"
+	fi
 done
 CCMS_LIST="${CCMS_LIST%?}]"
 
@@ -202,9 +274,8 @@ if [[ $DB_NODES == "-no_param" ]]; then
 fi
 
 # And turn them into a formatted list
-DB_NODES_ARRAY=$(echo $DB_NODES | tr " " "\n")
 DB_NODES_LIST="["
-for DB_NODE in $DB_NODES_ARRAY
+for DB_NODE in $DB_NODES
 do
     DB_NODES_LIST="$DB_NODES_LIST\"\\\'$DB_NODE\\\'\","
 done
@@ -215,7 +286,7 @@ DB_NODES_LIST="${DB_NODES_LIST%?}]"
 # PUT CONFIGURATION INTO 'VM.ARGS' AND 'SYS.CONFIG'
 
 echo " "
-echo "==========================================================="
+echo "-------"
 echo "Applying configuration:"
 echo " "
 echo "NODE_NAME = $NODE_NAME"
@@ -243,12 +314,12 @@ sed -i "s/-veil_cluster_node db_nodes.*/-veil_cluster_node db_nodes $DB_NODES_LI
 # Remove config for distributed application from sys.config
 sed -n -i '1h;1!H;${;g;s/\[.*%% SASL/\n %% SASL/g;p;}' ../releases/$APP_VSN/sys.config
 
-# If this node is a ccm, create a proper entry
-if [ $NODE_TYPE == 'ccm' ]; then
+# If this node is a ccm and there is at least two of CCM nodes in the cluster, create a proper DA entry
+if [[ $NODE_TYPE == 'ccm' ]] && [[ $OPT_CCM != "" ]]; then
 
 	# Produce list of ccms: [main_ccm, {opt_ccm1, opt_ccm2...}]
 	CCM_HIERARCHY_LIST="['$MAIN_CCM', {"
-	for OPT_CCM in $OPT_CCMS_ARRAY
+	for OPT_CCM in $OPT_CCMS
 	do
 	    CCM_HIERARCHY_LIST="$CCM_HIERARCHY_LIST'$OPT_CCM',"
 	done
@@ -259,7 +330,7 @@ if [ $NODE_TYPE == 'ccm' ]; then
 	if [ $NODE_NAME != $MAIN_CCM ]; then
 		CCM_SYNC_LIST="['$MAIN_CCM', "
 	fi
-	for OPT_CCM in $OPT_CCMS_ARRAY
+	for OPT_CCM in $OPT_CCMS
 	do
 		if [ $NODE_NAME != $OPT_CCM ]; then
 	    	CCM_SYNC_LIST="$CCM_SYNC_LIST'$OPT_CCM', "
@@ -278,7 +349,7 @@ if [ $NODE_TYPE == 'ccm' ]; then
  },
  "
 
-# If this node is a worker, add only '[' that has been removed by sed
+# If this node is a worker or an only CCM, add only '[' that has been removed by sed
 else
 	DIST_APP_CFG="["
 fi
@@ -295,7 +366,7 @@ echo " "
 echo "Done."
 
 # Check for '-console' option (-console overrides -start)
-INDEX=`awk -v a="$*" -v b="-console" 'BEGIN{print index(a, b)}'`
+INDEX=`awk -v a=" $* " -v b=" -console " 'BEGIN{print index(a, b)}'`
 if [[ $INDEX -gt 0 ]]; then
 
 	# User requested starting the node with console
@@ -309,7 +380,7 @@ if [[ $INDEX -gt 0 ]]; then
 
 else
 	# Check for '-start' option
-	INDEX=`awk -v a="$*" -v b="-start" 'BEGIN{print index(a, b)}'`
+	INDEX=`awk -v a=" $* " -v b=" -start " 'BEGIN{print index(a, b)}'`
 	if [[ $INDEX -gt 0 ]]; then
 
 		# User requested starting the node
@@ -320,7 +391,7 @@ else
 		../bin/veil_cluster_node start
 		../bin/veil_cluster_node ping
 
-		# The node failed to start
+		# The node failed to start or is not responding to pings
         if [ $? -ne 0 ]; then
             echo ""
             echo "Error during start of the node or it doesn't respond to pings."
